### ISSUE TITLE
Go-live configuration checklist.

### ISSUE THREAD

**Issue by benlk** [INN/umbrella-workdayminn#18]
Use this checklist to keep track of config items.

**Comment by joshdarby** [comment]
- [ ] Create staging branch + staging environment

**Comment by benlk** [comment]
- [ ] Homepage Bottom widgets
    - Recent Posts, 6, 140px widget, not constrained
    - Link Roundups, 4, thumbnails, no excerpts
- [ ] Homepage Sidebar widgets
    - Recent Posts, 1, 140px widget, constrained to "media" category
- [ ] Article Bottom widgets
    - Recent Posts, 3, 140px widget, not constrained

**Comment by joshdarby** [comment]
- [ ] Turn off Flywheel development mode

**Comment by kaylima** [comment]
@MirandaEcho the only thing left is to note in their GA account the day they went live so they can (hopefully) track the engagement spike
