### ISSUE TITLE
content todo's before launch

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-workdayminn#50]
- [x] remove all test content
- [x] make sure all homepage posts have featured media
- [x] make sure we have at least 4 links in the news aggregator
- [x] confirm the main menu
- [x] make sure that all recent videos/podcasts/audio are using top terms
- [x] remove "uncategorized" category from homepage posts

**Comment by MirandaEcho** [comment]
- [ ] Add additional footer logos to footer

**Comment by MirandaEcho** [comment]
- [ ] Add favicon
